### ISSUE TITLE
Add contactfield value in url parameter ?

### ISSUE THREAD

**Issue by leooxx** [ChrisRAoW/mautic-rss-to-email-bundle#4]
Hello,

I'm using your plugin every month to send the last posts from my blog and it work's great. Thank you so much.

I want to send a personnalised rss content to my client. Can i add a mautic parameter in the URL ?

Something like that...

{feed url="https://mywebsite/file.rss"} **+** {contactfield=id}  **=** {feed url="https://mywebsite/file.rss?clientId={contactfield=id}"}

Thank you for your reply,
Léo

**Comment by ChrisRAoW** [comment]
HI Léo,

Thanks for you suggestion. It's certainly something I had in mind already, but there is 1 big concern for this: performance.

By making the RSS file personalised it needs to be requested and parsed for every mail sent. When you have a big list it will cause a high load on the server and and brute-forced fetch of rss files to the target server. 

So that's why I didn't yet implemented it. But maybe will in the future.

Chris

**Comment by leooxx** [comment]
I thought the mail was generated for each sending for each user... as it contains other variables. 
So there are two levels of mail generation. The integration of RSS content and then the variables?

If the RSS is loaded only once... I understand. 
Thank you,

Léo

**Comment by leooxx** [comment]
Si j'envoi 1000 emails sur plusieurs heures et que j'ajoute un article dans mon flux les derniers emails sont différents des premiers...

**Comment by leooxx** [comment]
If I send 1000 emails over several hours and I post an article in my feed the last emails are different from the first ones in mautic...

**Comment by ttencate** [comment]
Isn't this [already implemented](https://github.com/ChrisRAoW/mautic-rss-to-email-bundle/blob/5f47011623671271551c1a59bb427d2532c5f69c/Parser/Parser.php#L23)? It seems to work for me.

**Comment by ChrisRAoW** [comment]
@ttencate It's already some time ago i worked on the plugin. But I could be that this was implemented by a pull request. Don't know anymore :-)
